using Pkg

Pkg.develop(url="/home/wester/Projects/Julia/Utilities/SimpleLog.jl")
Pkg.develop(url="/home/wester/Projects/Julia/Utilities/SpecialFileIO.jl")
Pkg.develop(url="/home/wester/Projects/Julia/Physics/PhysConst.jl")

#Pkg.rm("SimpleLog")
#Pkg.rm("SpecialFileIO")
#Pkg.rm("PhysConst")

#Pkg.add("Arrow")
Pkg.add("CPUTime")
Pkg.add("CSV")
Pkg.add("DataFrames")
#Pkg.add("DataInterpolations")
Pkg.add("DataStructures")
#Pkg.add("DelimitedFiles")
#Pkg.add("Documenter")
Pkg.add("HDF5")
Pkg.add("Interpolations")
#Pkg.add("JSON")
Pkg.add("JSON3")
Pkg.add("Parameters")
Pkg.add("Printf")
Pkg.add("PyPlot")
#Pkg.add("QuadGK")
#Pkg.add("SimpleLog")
#Pkg.add("SpecialFileIO")
Pkg.add("StaticArrays")
#Pkg.add("Statistics")
#Pkg.add("StatsBase")
